name: Check PoE characters for recipe matches
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'npm'
    - run: npm ci
    - name: start
      run: npm start
      env:
        ACCOUNT_NAME: ${{ secrets.ACCOUNT_NAME }}
        LEAGUE: ${{ secrets.LEAGUE }}
        POESESSID: ${{ secrets.POESESSID }}
        GLASSBLOWERS_BAUBLE_ENABLED: ${{ secrets.GLASSBLOWERS_BAUBLE_ENABLED }}